model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 2
        dataset: ['ValetParking']
        path: ['/data/datasets/ValetParking_exp']
        split: ['data_splits/vp_sampling.txt']
        depth_type: ['']
        repeat: [2]
    validation:
        dataset: ['ValetParking']
        path: ['/data/datasets/ValetParking_exp']
        split: ['data_splits/vp_sampling.txt']
        depth_type: ['']
    test:
        dataset: ['ValetParking']
        path: ['/data/datasets/ValetParking_exp']
        split: ['data_splits/vp_sampling.txt']
